"""Generate responsive WebP variants of the gallery photography.

Images/ holds the originals straight off the camera - 190 files, 209 MB, many of
them 6000x4000. Nothing on the site displays them above ~590 CSS px (grid cards
sit in a 320px-min multi-column layout; the lightbox art panel is 1.2fr of a
1080px grid), so every visitor was downloading roughly ten times the pixels they
could see.

This writes a derivative tree under img/ at three widths:

    480   grid cards at DPR 1
    960   grid cards at DPR 2, lightbox at DPR 1
    1600  lightbox at DPR 2, and phone lightboxes at DPR 3

Paths are slugified on the way out. 73 of the originals have spaces in their
names and srcset is a comma-and-space-delimited format, so keeping spaces out of
the derivative names removes a whole class of URL-encoding bug.

A manifest (img/manifest.json) records the intrinsic size of each variant so the
page can emit width/height and avoid layout shift.

Run from the repo root:  python tools/encode-images.py
Requires Pillow:         pip install Pillow
"""
import json
import os
import re
import sys

from PIL import Image

Image.MAX_IMAGE_PIXELS = None

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "Images")
OUT_DIR = os.path.join(ROOT, "img")

WIDTHS = [480, 960, 1600]
QUALITY = 80
METHOD = 4  # 6 is ~1% smaller and several times slower; not worth it at this count

SKIP_DIRS = {"Video"}
EXTS = (".webp", ".jpg", ".jpeg", ".png")


def slug(text):
    """Lowercase, ASCII, no spaces - safe to drop straight into a srcset."""
    text = re.sub(r"[^\w\s.-]", "", text)
    text = re.sub(r"[\s_]+", "-", text.strip())
    return re.sub(r"-+", "-", text).lower()


def slug_path(rel):
    parts = rel.replace("\\", "/").split("/")
    stem, _ = os.path.splitext(parts[-1])
    return "/".join([slug(p) for p in parts[:-1]] + [slug(stem)])


def write_lookup(manifest):
    """Emit js/gallery-images.js: original path -> [base, w, h, [[suffix, width]]].

    gallery.html keeps referencing the original Images/... paths in its ITEMS
    array, so nobody has to hand-edit 190 entries when the artwork changes.
    This table is what turns one of those paths into a srcset at render time.

    122 of the originals are narrower than the 1600 tier, so several of their
    variants come out at identical widths. Duplicate w-descriptors in a srcset
    are wasted bytes at best, so only the smallest suffix that produced a given
    width is kept.
    """
    lines = []
    for src in sorted(manifest):
        e = manifest[src]
        base = None
        seen_widths = {}
        pairs = []
        for w in WIDTHS:
            v = e["variants"][str(w)]
            if base is None:
                base = v["path"][: -len("-%d.webp" % w)]
            if v["w"] in seen_widths:
                continue
            seen_widths[v["w"]] = True
            pairs.append([w, v["w"]])
        lines.append("%s:[%s,%d,%d,%s]" % (
            json.dumps("Images/" + src), json.dumps(base), e["w"], e["h"],
            json.dumps(pairs, separators=(",", ":"))))

    out = os.path.join(ROOT, "js", "gallery-images.js")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/encode-images.py - do not edit by hand.\n"
                 "   Maps each original Images/... path to its responsive WebP\n"
                 "   variants: [basePath, intrinsicW, intrinsicH, [[suffix, realW]]].\n"
                 "   The suffix is the filename tier; realW is the true pixel width,\n"
                 "   which differs whenever the original was smaller than the tier. */\n")
        fh.write("window.FOX_IMAGES={\n")
        fh.write(",\n".join(lines))
        fh.write("\n};\n")
    print("   js/gallery-images.js  %.0f KB  (%d entries)"
          % (os.path.getsize(out) / 1024, len(lines)))


def main():
    if not os.path.isdir(SRC_DIR):
        sys.exit("no Images/ directory at " + SRC_DIR)

    sources = []
    for root, dirs, files in os.walk(SRC_DIR):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            if f.lower().endswith(EXTS):
                full = os.path.join(root, f)
                sources.append((full, os.path.relpath(full, SRC_DIR)))
    sources.sort()

    manifest = {}
    total_in = total_out = 0
    collisions = {}

    for n, (full, rel) in enumerate(sources, 1):
        base = slug_path(rel)
        if base in collisions:
            sys.exit("slug collision: %r and %r both map to %r"
                     % (collisions[base], rel, base))
        collisions[base] = rel

        out_sub = os.path.join(OUT_DIR, os.path.dirname(base))
        os.makedirs(out_sub, exist_ok=True)

        src_bytes = os.path.getsize(full)
        total_in += src_bytes

        with Image.open(full) as im:
            im = im.convert("RGB") if im.mode not in ("RGB", "RGBA") else im
            ow, oh = im.size
            entry = {"src": rel.replace("\\", "/"), "w": ow, "h": oh, "variants": {}}

            for w in WIDTHS:
                # Never upscale - if the original is smaller, cap at its width so
                # the srcset descriptor still tells the browser the truth.
                target_w = min(w, ow)
                target_h = max(1, round(oh * target_w / ow))
                dst = os.path.join(OUT_DIR, "%s-%d.webp" % (base, w))

                # Re-runs are cheap: only encode what is missing or stale.
                fresh = (os.path.isfile(dst)
                         and os.path.getmtime(dst) >= os.path.getmtime(full))
                if not fresh:
                    if target_w == ow:
                        resized = im
                    else:
                        resized = im.resize((target_w, target_h), Image.LANCZOS,
                                            reducing_gap=3.0)
                    resized.save(dst, "WEBP", quality=QUALITY, method=METHOD)

                out_bytes = os.path.getsize(dst)
                total_out += out_bytes
                entry["variants"][str(w)] = {
                    "path": os.path.relpath(dst, ROOT).replace("\\", "/"),
                    "w": target_w,
                    "h": target_h,
                    "bytes": out_bytes,
                }

        manifest[rel.replace("\\", "/")] = entry

        if n % 20 == 0 or n == len(sources):
            print("  %3d/%d  %.0f MB in -> %.0f MB out"
                  % (n, len(sources), total_in / 1048576, total_out / 1048576),
                  flush=True)

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "manifest.json"), "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=1, sort_keys=True)

    write_lookup(manifest)

    per_tier = {str(w): 0 for w in WIDTHS}
    for entry in manifest.values():
        for w, v in entry["variants"].items():
            per_tier[w] += v["bytes"]

    print("\n%d images  %.1f MB -> %.1f MB across %d widths"
          % (len(sources), total_in / 1048576, total_out / 1048576, len(WIDTHS)))
    for w in WIDTHS:
        print("   %5dw tier: %6.1f MB  (what one visitor downloads at that size)"
              % (w, per_tier[str(w)] / 1048576))


if __name__ == "__main__":
    main()
